'use strict';

const router = require('express').Router();
const { body, param, validationResult } = require('express-validator');
const { authenticate, requireRole, requireAnyKnownRole } = require('../middleware/auth');
const { peerContext }  = require('../middleware/peerContext');
const { wrap, parseResult } = require('../middleware/errorHandler');
const { initVisit, fetchByCID, pinJSON } = require('../fabric/ipfsClient');
const logger = require('../config/logger');

const canManage    = [authenticate, requireRole('receptionist', 'admin'), peerContext];
const canDischarge = [authenticate, requireRole('admin'), peerContext];
const canRead      = [authenticate, requireAnyKnownRole, peerContext];

// ── GET /visits — ListAllVisits ───────────────────────────────
router.get('/', ...canRead, wrap(async (req, res) => {
  const result = await req.contract.evaluateTransaction('VisitContract:ListAllVisits');
  return res.json({ success: true, data: parseResult(result) });
}));

// ── POST /visits — OpenVisit ──────────────────────────────────
// 1. Pin empty visit JSON to IPFS (gets visitId from patient's visitCount+1)
//    Problem: visitId is generated by chaincode. So we must derive it first.
//    Solution: read patient visitCount, derive visitId, pin, then submit.
router.post('/',
  ...canManage,
  [
    body('patientId').trim().notEmpty().withMessage('patientId required'),
    body('chiefComplaint').optional().isString(),
  ],
  wrap(async (req, res) => {
    const errors = validationResult(req);
    if (!errors.isEmpty()) return res.status(400).json({ success: false, errors: errors.array() });

    const { patientId, chiefComplaint = '' } = req.body;
    logger.info('OpenVisit', { patientId, userId: req.user.userId });

    // Step 1 — get patient's current visitCount to derive the new visitId
    const patientResult = await req.contract.evaluateTransaction(
      'PatientContract:GetPatient', patientId
    );
    const patient = parseResult(patientResult);
    if (!patient) return res.status(404).json({ success: false, error: `Patient not found: ${patientId}` });

    const visitNumber = (patient.visitCount || 0) + 1;
    const visitId = `${patientId}-V${visitNumber}`;

    // Step 2 — pin empty visit JSON to IPFS
    const { cid: visitCID } = await initVisit(visitId, patientId, chiefComplaint, req.user.userId);
    logger.info('Visit JSON pinned to IPFS', { visitId, visitCID });

    // Step 3 — open visit on blockchain (pass visitCID)
    const result = await req.contract.submitTransaction(
      'VisitContract:OpenVisit', patientId, chiefComplaint, visitCID
    );
    return res.status(201).json({ success: true, data: parseResult(result) });
  })
);

// ── GET /visits/:id — GetVisit ────────────────────────────────
router.get('/:id',
  ...canRead,
  wrap(async (req, res) => {
    const result = await req.contract.evaluateTransaction(
      'VisitContract:GetVisit', req.params.id
    );
    return res.json({ success: true, data: parseResult(result) });
  })
);

// ── GET /visits/:id/history ───────────────────────────────────
router.get('/:id/history',
  ...canRead,
  wrap(async (req, res) => {
    const result = await req.contract.evaluateTransaction(
      'VisitContract:GetVisitHistory', req.params.id
    );
    return res.json({ success: true, data: parseResult(result) });
  })
);

// ── GET /visits/:id/cids — CID history ───────────────────────
router.get('/:id/cids',
  ...canRead,
  wrap(async (req, res) => {
    const result = await req.contract.evaluateTransaction(
      'VisitContract:GetCIDHistory', req.params.id
    );
    return res.json({ success: true, data: parseResult(result) });
  })
);

// ── GET /visits/:id/ipfs — full IPFS content ─────────────────
// Fetch the actual clinical JSON from IPFS for a visit
router.get('/:id/ipfs',
  ...canRead,
  wrap(async (req, res) => {
    const visitResult = await req.contract.evaluateTransaction(
      'VisitContract:GetVisit', req.params.id
    );
    const visit = parseResult(visitResult);
    if (!visit) return res.status(404).json({ success: false, error: 'Visit not found' });
    if (!visit.visitCID) return res.json({ success: true, data: null });
    const clinical = await fetchByCID(visit.visitCID);
    return res.json({ success: true, data: { ...visit, clinical } });
  })
);

// ── PUT /visits/:id/doctor — AssignDoctor ─────────────────────
// Fetch visit JSON → add forwardingLog entry → repin → AssignDoctor(visitCID)
router.put('/:id/doctor',
  ...canManage,
  [
    param('id').trim().notEmpty(),
    body('doctorId').trim().notEmpty().withMessage('doctorId required'),
  ],
  wrap(async (req, res) => {
    const errors = validationResult(req);
    if (!errors.isEmpty()) return res.status(400).json({ success: false, errors: errors.array() });

    const visitId = req.params.id;
    const { doctorId } = req.body;
    logger.info('AssignDoctor', { visitId, doctorId, userId: req.user.userId });

    // Fetch current visit JSON and update forwardingLog
    const visitOnChain = parseResult(await req.contract.evaluateTransaction('VisitContract:GetVisit', visitId));
    const visitJson = await fetchByCID(visitOnChain.visitCID);
    visitJson.assignedDoctor = doctorId;
    visitJson.forwardingLog.push({
      action: 'DOCTOR_ASSIGNED', from: req.user.userId, fromRole: req.user.role,
      to: doctorId, toRole: 'doctor', notes: '', timestamp: new Date().toISOString(),
    });
    visitJson.updatedAt = new Date().toISOString();
    const newCID = await pinJSON(visitJson, `visit-${visitId}-doctor.json`);

    const result = await req.contract.submitTransaction(
      'VisitContract:AssignDoctor', visitId, doctorId, newCID
    );
    return res.json({ success: true, data: parseResult(result) });
  })
);

// ── PUT /visits/:id/nurse — AssignNurse ──────────────────────
router.put('/:id/nurse',
  ...canManage,
  [
    param('id').trim().notEmpty(),
    body('nurseId').trim().notEmpty().withMessage('nurseId required'),
  ],
  wrap(async (req, res) => {
    const errors = validationResult(req);
    if (!errors.isEmpty()) return res.status(400).json({ success: false, errors: errors.array() });

    const visitId = req.params.id;
    const { nurseId } = req.body;
    logger.info('AssignNurse', { visitId, nurseId, userId: req.user.userId });

    const visitOnChain = parseResult(await req.contract.evaluateTransaction('VisitContract:GetVisit', visitId));
    const visitJson = await fetchByCID(visitOnChain.visitCID);
    visitJson.assignedNurse = nurseId;
    visitJson.forwardingLog.push({
      action: 'NURSE_ASSIGNED', from: req.user.userId, fromRole: req.user.role,
      to: nurseId, toRole: 'nurse', notes: '', timestamp: new Date().toISOString(),
    });
    visitJson.updatedAt = new Date().toISOString();
    const newCID = await pinJSON(visitJson, `visit-${visitId}-nurse.json`);

    const result = await req.contract.submitTransaction(
      'VisitContract:AssignNurse', visitId, nurseId, newCID
    );
    return res.json({ success: true, data: parseResult(result) });
  })
);

// ── PUT /visits/:id/discharge — DischargePatient ──────────────
router.put('/:id/discharge',
  ...canDischarge,
  [
    param('id').trim().notEmpty(),
    body('dischargeNotes').optional().isString(),
  ],
  wrap(async (req, res) => {
    const visitId = req.params.id;
    const { dischargeNotes = '' } = req.body;
    logger.info('DischargePatient', { visitId, userId: req.user.userId });

    const visitOnChain = parseResult(await req.contract.evaluateTransaction('VisitContract:GetVisit', visitId));
    const visitJson = await fetchByCID(visitOnChain.visitCID);
    visitJson.dischargeNotes = dischargeNotes;
    visitJson.dischargedBy   = req.user.userId;
    visitJson.dischargedAt   = new Date().toISOString();
    visitJson.forwardingLog.push({
      action: 'PATIENT_DISCHARGED', from: req.user.userId, fromRole: 'admin',
      to: '', toRole: '', notes: dischargeNotes, timestamp: new Date().toISOString(),
    });
    visitJson.updatedAt = new Date().toISOString();
    const newCID = await pinJSON(visitJson, `visit-${visitId}-discharge.json`);

    const result = await req.contract.submitTransaction(
      'VisitContract:DischargePatient', visitId, newCID
    );
    return res.json({ success: true, data: parseResult(result) });
  })
);

module.exports = router;
