'use strict';

const { Contract } = require('fabric-contract-api');
const {
  requireRole,
  getCallerIdentity,
  makeLabRequestId,
  now,
  getState,
  putState,
} = require('./accessControl');
const { visitKey, VISIT_STATUS } = require('./visitContract');

class ForwardContract extends Contract {
  constructor() {
    super('ForwardContract');
  }

  // ── ForwardToNurse ────────────────────────────────────────────────────────
  // Doctor forwards patient to nurse. Status → WITH_NURSE.
  // visitCID: backend has already appended to forwardingLog in IPFS JSON + repinned.
  async ForwardToNurse(ctx, visitId, visitCID) {
    const { userId } = requireRole(ctx, 'doctor');

    const visit = await getState(ctx, visitKey(visitId));
    if (!visit) throw new Error(`Visit not found: ${visitId}`);

    if (!['WITH_DOCTOR', 'WITH_NURSE', 'WITH_LAB'].includes(visit.status)) {
      throw new Error(`Cannot forward to nurse from status '${visit.status}'`);
    }
    if (!visit.assignedNurse) {
      throw new Error('No nurse assigned. Assign a nurse first via AssignNurse.');
    }

    visit.status = VISIT_STATUS.WITH_NURSE;
    if (visitCID) {
      visit.cidHistory.push({ cid: visitCID, updatedBy: userId, updatedAt: now(), reason: 'FORWARD_TO_NURSE' });
      visit.visitCID = visitCID;
    }

    await putState(ctx, visitKey(visitId), visit);
    return JSON.stringify(visit);
  }

  // ── ForwardToDoctor ───────────────────────────────────────────────────────
  // Nurse forwards patient back to doctor. Status → WITH_DOCTOR.
  async ForwardToDoctor(ctx, visitId, visitCID) {
    const { userId } = requireRole(ctx, 'nurse');

    const visit = await getState(ctx, visitKey(visitId));
    if (!visit) throw new Error(`Visit not found: ${visitId}`);

    if (visit.status !== VISIT_STATUS.WITH_NURSE) {
      throw new Error(`Visit must be WITH_NURSE. Current: '${visit.status}'`);
    }
    if (!visit.assignedDoctor) {
      throw new Error('No doctor assigned to this visit.');
    }

    visit.status = VISIT_STATUS.WITH_DOCTOR;
    if (visitCID) {
      visit.cidHistory.push({ cid: visitCID, updatedBy: userId, updatedAt: now(), reason: 'FORWARD_TO_DOCTOR' });
      visit.visitCID = visitCID;
    }

    await putState(ctx, visitKey(visitId), visit);
    return JSON.stringify(visit);
  }

  // ── ForwardToLab ──────────────────────────────────────────────────────────
  // Doctor requests lab tests. Status → WITH_LAB.
  // visitCID: backend has already added labRequest entry to IPFS JSON + repinned.
  // labRequestId: generated by backend (using makeLabRequestId pattern) and
  //               stored in the IPFS JSON — passed here for event logging.
  async ForwardToLab(ctx, visitId, labRequestId, visitCID) {
    const { userId } = requireRole(ctx, 'doctor');

    const visit = await getState(ctx, visitKey(visitId));
    if (!visit) throw new Error(`Visit not found: ${visitId}`);

    if (!['WITH_DOCTOR', 'WITH_NURSE', 'WITH_LAB'].includes(visit.status)) {
      throw new Error(`Cannot forward to lab from status '${visit.status}'`);
    }
    if (!labRequestId) throw new Error('labRequestId is required');
    if (!visitCID)     throw new Error('visitCID is required');

    visit.status = VISIT_STATUS.WITH_LAB;
    visit.cidHistory.push({
      cid: visitCID, updatedBy: userId, updatedAt: now(),
      reason: `FORWARD_TO_LAB:${labRequestId}`,
    });
    visit.visitCID = visitCID;

    await putState(ctx, visitKey(visitId), visit);
    return JSON.stringify(visit);
  }

  // ── LabResultsBackToDoctor ────────────────────────────────────────────────
  // After lab supervisor approves results. Status → WITH_DOCTOR.
  // visitCID: backend has updated IPFS JSON with approval info.
  async LabResultsBackToDoctor(ctx, visitId, labRequestId, visitCID) {
    const { userId } = requireRole(ctx, 'labsupervisor', 'labadmin', 'admin');

    const visit = await getState(ctx, visitKey(visitId));
    if (!visit) throw new Error(`Visit not found: ${visitId}`);

    visit.status = VISIT_STATUS.WITH_DOCTOR;
    if (visitCID) {
      visit.cidHistory.push({
        cid: visitCID, updatedBy: userId, updatedAt: now(),
        reason: `LAB_RESULTS_RETURNED:${labRequestId}`,
      });
      visit.visitCID = visitCID;
    }

    await putState(ctx, visitKey(visitId), visit);
    return JSON.stringify(visit);
  }
}

module.exports = { ForwardContract };
